# Generated by Django 3.2.4 on 2023-06-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_comment_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrs',
            old_name='phone_number',
            new_name='number',
        ),
    ]
