# Generated by Django 3.2.4 on 2023-06-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_phone_number_followrs_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followrs',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='followrs',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
